---
title: "Investment"
author: "Nanthawat Anancharoenpakorn"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: true  # Table of contents
    toc_depth: 3  # Depth of headers to include in contents
---

```{r library, message=TRUE, warning=FALSE, include=FALSE}
# Dependencies
# Load the required libraries
library(googlesheets4)
library(tidyverse)
library(xts)
library(knitr)
library(quantmod)
library(readr)
library(xts)
library(PerformanceAnalytics)
library(ggplot2)
source('/Users/nanthawat/Documents/GitHub/AnanCapital/R/Function/strategy_testing/moving_average_crossover.R')
source('/Users/nanthawat/Documents/GitHub/AnanCapital/R/Function/indicators.R')
source('/Users/nanthawat/Documents/GitHub/AnanCapital/R/Data/import_data.R')
source('/Users/nanthawat/Documents/GitHub/AnanCapital/R/Function/simulate_independently.R')
source('/Users/nanthawat/Documents/GitHub/AnanCapital/R/Data/generate_random_data.R')


```

# Investment Analysis using First Principle Analysis

## 1. Define Fundamental Principle

1. Market can go up and down. There is no pre-defined function that hide behind price movement. 
2. High volatility will wipe out initial capital. 

## 2. Break down the problem

1. We need to make money by maximize profit function f(weight) =  X * weight, where X is a random variable of daily return.

## 3. Analyze from the groud up

## 4. Synthesize information

1. Invest Buy and Hold to many asset class [benefit from market and diversification]
2. Apply TF strategy to each market class [Exploit behavior alpha]
3. Apply TF across asset class [Benefit Additonally from diversification ]


## 5. Apply and Test 

1. Test that buy and hold is add value[Skip]
2. Test if Sharpe ratio of TF after cost is significantly higher than static buy and hold. 
3. Test if we construct portfolio of TF system significantly has higher Sharpe. 




